### ISSUE TITLE
شرح دروس

### ISSUE THREAD

**Issue by SabraHashemi** [HsnFirooz/University-of-Isfahan#1]
salam aghaye firooz, 
man donbale sharhe doros bara daneshgah esfahan hastam k b in repo barkhordam :)
ma computeria bazgashetemoon hamishe b githube :) 
mishe rahnamai konid mano? email darid k bahaton ertebat mopstaghim begiram?

**Comment by SabraHashemi** [comment]
alan didam emailo :)

**Comment by hsnfirooz** [comment]
It was solved over an email.
